
name: Python CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify the Python version you need

      # check the quality of all Python modules using Ruff
      # No need for requirements file just one module to download
      - name: code formatting Ruff
        run: |
          python -m pip install --upgrade pip
          pip install back 

      - name: Check code quality with Ruff
        run: |
          ruff --check .


      # check the quality of all Python modules using Ruff
      - name: code formatting Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check code quality with Ruff
        run: |
          ruff check .
